models_repo = {
    "box": {
        "obj_filename": "caixa/caixa.obj",
        "texture_filename": "caixa/caixa.jpg",
        "draw_type": "TRIANGLE",
        "translation": [-26, 0.8, -18],
        "scale": [0.6, 0.6, 0.6],
        "angles": [0, 0, 0],
    },
    "skybox": {
        "obj_filename": "sky/sky.obj",
        "texture_filename": "sky/sky.png",
        "draw_type": "TRIANGLE",
        "translation": [0, 0, 0],
        "scale": [3, 3, 3],
        "angles": [0, 0, 0],
    },
    "terrain_grass": {
        "obj_filename": "terrain/terreno.obj",
        "texture_filename": "terrain/grass.jpg",
        "draw_type": "TRIANGLE",
        "translation": [0, 0, 0],
        "scale": [200, 1, 200],
        "angles": [0, 0, 0],
    },
    "terrain_sand": {
        "obj_filename": "terrain/terreno.obj",
        "texture_filename": "terrain/sand.jpeg",
        "draw_type": "TRIANGLE",
        "translation": [25, 0.1, 50],
        "scale": [50, 1, 50],
        "angles": [0, 0, 0],
    },
    "small_skull": {
        "obj_filename": "skull/skull.obj",
        "texture_filename": "skull/skull.jpg",
        "draw_type": "QUADS",
        "translation": [-26, 2, -23],
        "scale": [0.07, 0.07, 0.07],
        "angles": [-90, 45, 0],
    },
    "big_skull": {
        "obj_filename": "skull/skull.obj",
        "texture_filename": "skull/skull.jpg",
        "draw_type": "QUADS",
        "translation": [65, 29, 15],
        "scale": [0.7, 0.7, 0.7],
        "angles": [-90, 0, 0],
    },
    "pineapple": {
        "obj_filename": "pineapple/pineapple.obj",
        "texture_filename": "pineapple/pineapple.jpg",
        "draw_type": "QUADS",
        "translation": [-26, 1.4, -18],
        "scale": [0.06, 0.06, 0.06],
        "angles": [-90, 0, 0],
    },
    "cat": {
        "obj_filename": "cat/cat.obj",
        "texture_filename": "cat/cat.jpg",
        "draw_type": "QUADS",
        "translation": [-17, 0.66, -8],
        "scale": [0.042, 0.042, 0.042],
        "angles": [-90, 100, 0],
    },
    "watchtower": {
        "obj_filename": "watchtower/watchtower.obj",
        "texture_filename": "watchtower/watchtower.jpg",
        "draw_type": "QUADS",
        "translation": [65, -3, 15],
        "scale": [2, 3.5, 2],
        "angles": [0, 0, 0],
    },
    "farmhouse": {
        "obj_filename": "farmhouse/farmhouse_adjusted.obj",
        "texture_filename": "farmhouse/farmhouse.jpg",
        "draw_type": "TRIANGLE",
        "translation": [-20, 0, -15],
        "scale": [0.5, 0.5, 0.5],
        "angles": [0, -135, 0],
    },
}
