models_repo = {
    "box": {
        "obj_filename": "caixa/caixa.obj",
        "texture_filename": "caixa/caixa.jpg",
        "draw_type": "TRIANGLE",
        "translation": [0, 0, 15],
        "scale": [1, 1, 1],
        "angles": [0, 0, 0],
    },
    "skybox": {
        "obj_filename": "sky/sky.obj",
        "texture_filename": "sky/sky.png",
        "draw_type": "TRIANGLE",
        "translation": [0, 0, 0],
        "scale": [3, 3, 3],
        "angles": [0, 0, 0],
    },
    "terrain_grass": {
        "obj_filename": "terrain/terreno.obj",
        "texture_filename": "terrain/grass.jpg",
        "draw_type": "TRIANGLE",
        "translation": [0, -1.01, 0],
        "scale": [200, 200, 200],
        "angles": [0, 0, 0],
    },
    "terrain_sand": {
        "obj_filename": "terrain/terreno.obj",
        "texture_filename": "terrain/sand.jpeg",
        "draw_type": "TRIANGLE",
        "translation": [20, -1, 0],
        "scale": [10, 10, 10],
        "angles": [0, 0, 0],
    },
    "small_skull": {
        "obj_filename": "skull/skull.obj",
        "texture_filename": "skull/skull.jpg",
        "draw_type": "QUADS",
        "translation": [30, 4, 0],
        "scale": [0.3, 0.3, 0.3],
        "angles": [-90, 0, 0],
    },
    "big_skull": {
        "obj_filename": "skull/skull.obj",
        "texture_filename": "skull/skull.jpg",
        "draw_type": "QUADS",
        "translation": [30, 4, 0],
        "scale": [1, 1, 1],
        "angles": [0, 0, 0],
    },
    "pineapple": {
        "obj_filename": "pineapple/pineapple.obj",
        "texture_filename": "pineapple/pineapple.jpg",
        "draw_type": "QUADS",
        "translation": [10, 4, 10],
        "scale": [0.3, 0.3, 0.3],
        "angles": [0, 0, 0],
    },
    "cat": {
        "obj_filename": "cat/cat.obj",
        "texture_filename": "cat/cat.jpg",
        "draw_type": "QUADS",
        "translation": [30, 4, 5],
        "scale": [0.3, 0.3, 0.3],
        "angles": [0, 0, 0],
    },
    "watchtower": {
        "obj_filename": "watchtower/watchtower.obj",
        "texture_filename": "watchtower/watchtower.jpg",
        "draw_type": "QUADS",
        "translation": [10, 4, 10],
        "scale": [0.3, 0.3, 0.3],
        "angles": [0, 0, 0],
    },
    # {
    #     'obj_filename': 'farmhouse/farmhouse.obj',
    #     'texture_filename': 'farmhouse/farmhouse.jpg',
    #     'draw_type': 'QUADS',
    #     'angle': 0.0,
    #     'translation': [10.0, 4, 10.0],
    #     'rotation': [1.0, 1.0, 1.0],
    #     'scale': [0.3, 0.3, 0.3],
    # },
}
